package com.example.cleaning_service.providers.enums;

public enum EServiceType {
    RESIDENTIAL_CLEANING,
    COMMERCIAL_CLEANING,
    DEEP_CLEANING,
    MOVE_IN_OUT_CLEANING,
    POST_CONSTRUCTION_CLEANING,
    CARPET_CLEANING,
    WINDOW_CLEANING,
    UPHOLSTERY_CLEANING,
    FLOOR_POLISHING,
    SANITIZATION_SERVICES,
    MAID_SERVICE,
    OFFICE_CLEANING,
    GREEN_CLEANING,
    PRESSURE_WASHING
}