package com.example.cleaning_service.security.entities.permission;

public enum EPermission {
    CREATE_ACCOUNT,
    MANAGE_USERS, VIEW_REPORTS, MANAGE_ROLES, DELETE_ACCOUNTS,
    CREATE_ORDERS, CANCEL_ORDERS,
    VIEW_ASSIGNED_ORDERS, UPDATE_ORDER_STATUS,
    ASSIGN_CLEANERS, MONITOR_CLEANING_PROGRESS,
    RATE_CLEANERS, VIEW_ORDERS,
    RESPOND_TO_QUERIES, MANAGE_SCHEDULES
}
